rspirv: Update to 0.6.0
Fixes the following on 0.5.4:

    error[E0308]: mismatched types
       --> /home/marijn/.cargo/registry/src/github.com-1ecc6299db9ec823/rspirv-0.5.4/mr/constructs.rs:190:22
        |
    190 |             version: (spirv::MAJOR_VERSION << 16) | (spirv::MINOR_VERSION << 8),
        |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `u8`

Also fix line endings from CRLF -> LF in examples/include.rs.